services:
  resourcespace:
    build: .
    container_name: resourcespace
    restart: unless-stopped
    depends_on:
      - mariadb
    volumes:
      - filestore:/var/www/html/filestore
      - ./config.php:/var/www/html/include/config.php
    labels:
      katenary.v3/configmap-files: |-
        - ./config.php
      katenary.v3/ingress: |-
        port: 80
        hostname: mywebsite.com (optional)
    networks:
      - frontend
      - backend
    ports:
      - "80:80"

  mariadb:
    image: mariadb
    container_name: mariadb
    restart: unless-stopped
    env_file:
      - db.env
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - backend
    labels:
      katenary.v3/ports: |-
        - 3306

networks:
  frontend:
  backend:

volumes:
  mariadb:
  filestore:
