apiVersion: v1
data:
  config.php: ""
kind: ConfigMap
metadata:
  annotations:
    katenary.v3/compose-hash: 95e4a82d22f5978da3fcb0847f42ab03ac713fb1
    katenary.v3/version: master
  labels:
    {{- include "resourcespace_docker.labels" . | nindent 4 }}
    katenary.v3/component: resourcespace
  name: '{{ include "resourcespace_docker.fullname" . }}-resourcespace'
