apiVersion: v1
data:
  config.php: ""
kind: ConfigMap
metadata:
  annotations:
    katenary.v3/compose-hash: 130407091ed05d8753a6b9ecc272bb838a11d1ca
    katenary.v3/version: master
  labels:
    {{- include "resourcespace.labels" . | nindent 4 }}
    katenary.v3/component: resourcespace
  name: '{{ include "resourcespace.fullname" . }}-resourcespace'
