{{- if .Values.resourcespace.persistence.filestore.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    katenary.v3/compose-hash: 95e4a82d22f5978da3fcb0847f42ab03ac713fb1
    katenary.v3/version: master
  labels:
    {{- include "resourcespace_docker.labels" . | nindent 4 }}
    katenary.v3/component: resourcespace
  name: '{{ include "resourcespace_docker.fullname" . }}-resourcespace-filestore'
spec:
  accessModes:
  {{- .Values.resourcespace.persistence.filestore.accessMode | toYaml | nindent 2 }}
  resources:
    requests:
      storage: {{ tpl .Values.resourcespace.persistence.filestore.size $ }}
  {{- if ne .Values.resourcespace.persistence.filestore.storageClass "-" }}
  storageClassName: '{{ .Values.resourcespace.persistence.filestore.storageClass }}'
  {{- end }}

{{- end }}