{{- if .Values.resourcespace.ingress.enabled -}}
{{- $fullname := include "resourcespace.fullname" . -}}
{{- $tlsname := printf "%s-%s-tls" $fullname "resourcespace" -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    katenary.v3/compose-hash: 7f751bec0593ec34a43c687908476d1d61048907
    katenary.v3/version: svc4-a27a851
    {{- if .Values.resourcespace.ingress.annotations -}}
        {{- toYaml .Values.resourcespace.ingress.annotations | nindent 4 }}
    {{- end }}
  labels:
    {{- include "resourcespace.labels" . | nindent 4 }}
    katenary.v3/component: resourcespace
  name: '{{ $fullname }}-resourcespace'
spec:
  {{- if ne .Values.resourcespace.ingress.class "-" }}
  ingressClassName: '{{ tpl .Values.resourcespace.ingress.class $ }}'
  {{- end }}
  rules:
  - host: '{{ tpl .Values.resourcespace.ingress.host $ }}'
    http:
      paths:
      - backend:
          service:
            name: '{{ $fullname }}-resourcespace'
            port:
              name: http
        path: '{{ tpl .Values.resourcespace.ingress.path $ }}'
        pathType: ImplementationSpecific
  {{- if .Values.resourcespace.ingress.tls.enabled }}
  tls:
  - hosts:
    - '{{ tpl .Values.resourcespace.ingress.host . }}'
    secretName: '{{ .Values.resourcespace.ingress.tls.secretName | default $tlsname }}'
  {{ end -}}

{{- end -}}