apiVersion: v1
data:
  MYSQL_DATABASE: resourcespace
  MYSQL_PASSWORD: change-me
  MYSQL_ROOT_PASSWORD: change-me
  MYSQL_USER: resourcespace_rw
kind: ConfigMap
metadata:
  annotations:
    katenary.v3/compose-hash: 7ef9ff871f6607662d992bcbf313e5f61d10ae7a
    katenary.v3/version: master
  labels:
    {{- include "resourcespace_docker.labels" . | nindent 4 }}
    katenary.v3/component: mariadb
  name: '{{ include "resourcespace_docker.fullname" . }}-mariadb'
