apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    katenary.v3/compose-hash: 7ef9ff871f6607662d992bcbf313e5f61d10ae7a
    katenary.v3/version: master
  labels:
    {{- include "resourcespace_docker.labels" . | nindent 4 }}
    katenary.v3/component: mariadb
  name: '{{ include "resourcespace_docker.fullname" . }}-mariadb'
spec:
  replicas: {{ .Values.mariadb.replicas }}
  selector:
    matchLabels:
      {{- include "resourcespace_docker.selectorLabels" . | nindent 6 }}
      katenary.v3/component: mariadb
  strategy: {}
  template:
    metadata:
      labels:
        {{- include "resourcespace_docker.selectorLabels" . | nindent 8 }}
        katenary.v3/component: mariadb
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: '{{ include "resourcespace_docker.fullname" . }}-mariadb'
        image: '{{ tpl .Values.mariadb.repository.image $ }}:{{ tpl .Values.mariadb.repository.tag $ | default "latest" }}'
        imagePullPolicy: {{ .Values.mariadb.imagePullPolicy }}
        name: mariadb
        ports:
        - containerPort: 3306
          name: mysql
        {{- if .Values.mariadb.resources }}
        resources:
          {{ .Values.mariadb.resources | toYaml | nindent 10 }}
        {{- end }}
        volumeMounts:
        {{- if .Values.mariadb.persistence.mariadb.enabled }}
        - mountPath: /var/lib/mysql
          name: mariadb
        {{- end }}
      {{- if .Values.pullSecrets }}
      imagePullSecrets:
      {{- .Values.pullSecrets | toYaml | nindent 6 }}
      {{- end }}
      {{- if .Values.mariadb.nodeSelector }}
      nodeSelector:
        {{- .Values.mariadb.nodeSelector | toYaml | nindent 8 }}
      {{- end }}
      {{- if ne .Values.mariadb.serviceAccount "" }}
      serviceAccountName: {{ .Values.mariadb.serviceAccount | quote }}
      {{- end }}
      volumes:
      {{- if .Values.mariadb.persistence.mariadb.enabled }}
      - name: mariadb
        persistentVolumeClaim:
          claimName: '{{ include "resourcespace_docker.fullname" . }}-mariadb-mariadb'
      {{- end }}
