apiVersion: v1
kind: Service
metadata:
  annotations:
    katenary.v3/compose-hash: 130407091ed05d8753a6b9ecc272bb838a11d1ca
    katenary.v3/version: master
  labels:
    {{- include "resourcespace.labels" . | nindent 4 }}
    katenary.v3/component: mariadb
  name: '{{ include "resourcespace.fullname" . }}-mariadb'
spec:
  ports:
  - name: mysql
    port: 3306
    protocol: TCP
    targetPort: mysql
  selector:
    {{- include "resourcespace.selectorLabels" . | nindent 4 }}
    katenary.v3/component: mariadb
